<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DINM3YRLDN3" failures="1" tests="2" name="eCommerce" time="16.683" errors="0" timestamp="2025-08-29T13:41:30 IST">
  <testcase classname="ritabhSelenium.eCommerce.submitOrderTest" name="submitOrder" time="12.293"/>
  <testcase classname="ritabhSelenium.eCommerce.submitOrderTest" name="validateOrders" time="0.286">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="Index 2 out of bounds for length 2">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
at ritabhSelenium.eCommerce.pageObjects.ordersPage.validatOrdersList(ordersPage.java:36)
at ritabhSelenium.eCommerce.submitOrderTest.validateOrders(submitOrderTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- validateOrders -->
</testsuite> <!-- eCommerce -->
